### ISSUE TITLE
Charter and Membership agreement

### ISSUE THREAD

**Issue by sparrell** [OpenC2-org/docs-pub#1]
Does the charter exist? Is there a membership agreement? Should this be discussed at face to face meeting 9/29/16?

**Comment by sparrell** [comment]
Has there been any progress in this area? If not, can we add an agenda topic at face2face to discuss alternatives?

**Comment by jmbrule** [comment]
We do have a charter that was released by the OGC and we emailed it out to the primary POCs of our existing members.  
We can bring this up at the F2F (time permitting).

**Comment by sparrell** [comment]
Can we add to agenda to make sure time permits?

**Comment by sparrell** [comment]
Yeah! it exists
