### ISSUE TITLE
Align language description document 'target' field to current version of STIX

### ISSUE THREAD

**Issue by jyoverma** [OpenC2-org/docs-pub#3]
The language description document calls out the Cybox observables that could be used for target. In the new version it is called Cyber Observables and the objects are different from the older version. The document can call out the new objects for STIX 2.0. In addition there should be a pointer to Cybox since its a moving target.

**Comment by romanojd** [comment]
**This repository has been deprecated.**

The current OpenC2 Date Model can be found in the current Language Description Document.
